const { zokou } = require("../framework/zokou");
const { default: axios } = require("axios");

zokou(
  {
    nomCom: "pair",
    aliases: ["session", "pair", "paircode", "qrcode"],
    reaction: "🔔", // Notification icon
    categorie: "General",
  },
  async (dest, origine, msg) => {
    const { repondre, arg, sender } = msg;

    try {
      if (!arg || arg.length === 0) {
        return repondre("⚠️ *Please provide a number in the format:* `25578xxxxxxx`", { reply: true });
      }

      await repondre("🕓 *Please wait... DML-XMD is generating your Pair Code.*", { reply: true });

      const encodedNumber = encodeURIComponent(arg.join(" "));
      const apiUrl = `https://zokou-session.onrender.com/code?number=${encodedNumber}`;
      const response = await axios.get(apiUrl);
      const data = response.data;

      if (data?.code) {
        const pairCode = data.code;

        const notificationMessage = `
╔═══════════════════╗
🎯 *PAIR CODE READY!* 🎯
╚═══════════════════╝

🔗 \`\`\`${pairCode}\`\`\`

📲 *Copy the above code and link your WhatsApp via Linked Devices.*

⚙️ _Generated by DML-XMD Bot_
`;

        await repondre(notificationMessage, { reply: true });
      } else {
        throw new Error("Invalid response from API — no code found.");
      }
    } catch (error) {
      console.error("Error getting API response:", error.message);
      repondre(
        `
❌ *Error:* Could not get response from the pairing service.

Please try again later.
        `,
        { reply: true }
      );
    }
  }
);
