const { zokou } = require("../framework/zokou");
const { default: axios } = require("axios");

zokou(
  {
    nomCom: "pair1",
    aliases: ["session", "pair", "paircode", "qrcode"],
    reaction: "🔔",
    categorie: "General",
  },
  async (dest, origine, msg) => {
    const { repondre, arg, sender, zk } = msg;

    try {
      if (!arg || arg.length === 0) {
        return repondre(
          "⚠️ *Please provide a number in this format:* `25578xxxxxxx`",
          { reply: true }
        );
      }

      await repondre(
        "🕓 *Please wait... DML-XMD is generating your Pair Code.*",
        { reply: true }
      );

      const encodedNumber = encodeURIComponent(arg.join(" "));
      const apiUrl = `https://dml-md-session-urtj.onrender.com/code?number=${encodedNumber}`;
      const response = await axios.get(apiUrl);
      const data = response.data;

      if (data?.code) {
        const pairCode = data.code;

        // Send main message
        const textMessage = `
╔═══════════════════╗
🎯 *PAIR CODE READY!* 🎯
╚═══════════════════╝

🔗 \`\`\`${pairCode}\`\`\`

📲 *Click the button below to COPY your Pair Code.*

⚙️ *Generated by DML-XMD Bot*
`;

        // Send message with copy button
        await zk.sendMessage(dest, {
          text: textMessage,
          buttons: [
            {
              buttonId: `copy_${pairCode}`,
              buttonText: { displayText: "📋 COPY PAIR CODE" },
              type: 1,
            },
          ],
          headerType: 1,
        });

        // Listener for the button
        zk.ev.on("messages.upsert", async (m) => {
          try {
            const clicked = m.messages[0];
            if (!clicked.message.buttonsResponseMessage) return;

            const buttonId = clicked.message.buttonsResponseMessage.selectedButtonId;

            if (buttonId === `copy_${pairCode}`) {
              await zk.sendMessage(clicked.key.remoteJid, {
                text: pairCode,
              });
            }
          } catch {}
        });

      } else {
        throw new Error("Invalid response from API — no code found.");
      }
    } catch (error) {
      console.error("Error getting API response:", error.message);
      repondre(
        `
❌ *Error:* Could not get response from the pairing service.

Please try again later.
`,
        { reply: true }
      );
    }
  }
);
